#!/usr/bin/env node
/**
 * Generate the viewer's copy of the font kit from the MCP half's single
 * source of truth (mcp/src/fonts.rs + mcp/fonts/*.woff2).
 *
 * WHY A COPY EXISTS. Boards travel lean — every transit surface carries
 * `@font-face` declarations with their payloads ELIDED (the lean-transit
 * rule; full bytes live only in the plugin's database). The viewer therefore
 * owns the payloads and re-attaches them at display and export time. Two
 * kits only stay one kit if the copy is GENERATED, never hand-edited —
 * check-contracts.mjs fails the build when this file is stale.
 *
 *   node scripts/gen-fontkit.mjs        # rewrite src/lib/fontkit.generated.ts
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const VIEWER = resolve(HERE, "..");
const ROOT = resolve(VIEWER, "..");
const FONTS_RS = join(ROOT, "mcp", "src", "fonts.rs");
const FONTS_DIR = join(ROOT, "mcp", "fonts");
const OUT = join(VIEWER, "src", "lib", "fontkit.generated.ts");

/** Parse Face blocks out of fonts.rs — family name + (weight, file) pairs.
 * The shapes matched here are the literal ones in KIT; if fonts.rs grows a
 * new shape, this parse fails loudly rather than emitting a partial kit. */
export function parseKit(source) {
  const faces = [];
  const blocks = source.split(/Face\s*\{/).slice(1);
  for (const block of blocks) {
    const family = /family:\s*"([^"]+)"/.exec(block)?.[1];
    if (!family) continue;
    const weights = [...block.matchAll(/\((\d+),\s*include_bytes!\("\.\.\/fonts\/([^"]+)"\)\)/g)].map(
      (m) => ({ weight: Number(m[1]), file: m[2] }),
    );
    if (weights.length === 0) {
      throw new Error(`fonts.rs Face "${family}" matched no weights — parser and source drifted`);
    }
    faces.push({ family, weights });
  }
  if (faces.length === 0) throw new Error("fonts.rs yielded no Face blocks — parser and source drifted");
  return faces;
}

// Generation only when run as a script — check-contracts.mjs imports
// `parseKit` and must never trigger a rewrite of the file it is checking.
const runAsScript =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (runAsScript) {
  const kit = parseKit(readFileSync(FONTS_RS, "utf8"));

  const entries = [];
  for (const face of kit) {
    for (const { weight, file } of face.weights) {
      const bytes = readFileSync(join(FONTS_DIR, file));
      entries.push({
        family: face.family,
        weight,
        file,
        sha256: createHash("sha256").update(bytes).digest("hex"),
        b64: bytes.toString("base64"),
      });
    }
  }

  const body = entries
    .map(
      (e) =>
        `  {\n    family: ${JSON.stringify(e.family)},\n    weight: ${e.weight},\n` +
        `    file: ${JSON.stringify(e.file)},\n    sha256: ${JSON.stringify(e.sha256)},\n` +
        `    b64:\n      ${JSON.stringify(e.b64)},\n  }`,
    )
    .join(",\n");

  writeFileSync(
    OUT,
    `/**
 * GENERATED by scripts/gen-fontkit.mjs from mcp/src/fonts.rs + mcp/fonts/.
 * DO NOT EDIT — regenerate instead. check-contracts.mjs fails when stale.
 */
export interface KitFace {
  family: string;
  weight: number;
  file: string;
  sha256: string;
  b64: string;
}

export const KIT_FACES: KitFace[] = [
${body},
];
`,
  );
  console.log(`wrote ${OUT}: ${entries.length} face-weight(s), ${kit.length} family(ies)`);
}
